---

name: "CI"

on:
  push:

jobs:
  build-image:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Build image"
        uses: "docker/build-push-action@v6"
